name: bezier_kit
description: Bezier curves and paths in Dart for building vector applications
version: 0.1.2
homepage: https://www.lepsch.com/
repository: https://github.com/lepsch/bezier_kit/

environment:
  sdk: ^3.1.5

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.9

topics:
  - bezier
  - curve
  - quadratic
  - intersection
  - geometry
